name: dynamapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.12.0
  - jax >= 0.4.26
  - jaxlib >= 0.4.26
  - scipy >= 1.14.0
  # ==========================
  # Documentation dependencies
  # ==========================



  # ====================================
  # Optional dependencies for development
  # ====================================
  # [style]

